# Generated by Django 4.2.13 on 2024-09-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0035_created_updated_everywhere"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendlycaptchaSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("site_key", models.CharField(default="", max_length=200)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pretalx_friendlycaptcha_settings",
                        to="event.event",
                    ),
                ),
            ],
        ),
    ]
